### ISSUE TITLE
Texte qui dépasse des boutons

### ISSUE THREAD

**Issue by SolidOrphan** [maelsoucaze/flarum-ext-french#12]
Sur mon forum, "Démarrer une discussion" dépasse le bouton car la phrase est trop longue. Je l'ai remplacé par "Nouvelle discussion".

Quant à "Latest" par rapport à "Newest", tu as bien soulevé le problème de confusions entre les deux. Actuellement ça donne : 
Oldest: Anciens. Affiche les discussions par ordre croissant (date).
Latest: Récents. Affiche les discussions par ordre décroissant (date).
Newest: Nouveaux. Affiche les NOUVELLES créations (pas encore vu).

Je voudrais suggérer de remplacer "Latest" par "Derniers".
ça permet de voir plus clair et de bien différencier les deux (mon humble opinion).

**Comment by maelsoucaze** [comment]
Pour ce qui est du "Démarrer une discussion", c'est seulement un problème qui sera je pense corrigé dans une version ultérieure de Flarum. Je vais m'en tenir à laisser ça comme ça le temps que le bouton s'adapte au texte. C'est d'ailleurs pas le seul, si tu cliques dans tes réglages, puis dans "Modifier le mot de passe", tu verras le texte pour envoyer l'e-mail de réinitialisation du mot de passe qui dépasse largement du bouton.

Pour ce qui est de "Latest", que ce soit "Derniers" ou "Récents", ça rentre forcément en conflit avec "Nouveaux"... C'est pas évident. J'ai pensé à modifier "Nouveaux" par "Croissant" et "Anciens" par "Décroissant", tu en penses quoi ? Je trouverai ça plus compréhensible et différentiable mais ce n'est que mon avis, donc toute opinion est la bienvenue !

**Comment by SolidOrphan** [comment]
J'ai pensé à la même chose mais je me suis dis qu'un nouveau sur le forum ne saura pas nécessairement de quoi il en retourne (si c'est le nombre de message, etc). Mais si c'est possible d'agrandir la zone de texte, partir sur (dé)croissant paraît le plus judicieux avec un simple "Date (dé-croissant).

**Comment by SolidOrphan** [comment]
Après vérification, en écrivant " Date (dé-croissant)", le bouton s'agrandit automatiquement et ne dépasse pas. Je crois que c'est la meilleure solution (pour l'instant). C'est encore plus pertinent de mettre ceci si dans le futur, il y a plus de choix de choisir quels types d'affichage on souhaite voir. C'est tout benef'.

**Comment by maelsoucaze** [comment]
Le problème étant que cette traduction est toujours erronée, car il faudrait spécifier que c'est la date de création de la discussion qui est décroissante, et non la date de réponse dans une discussion. :(

**Comment by SolidOrphan** [comment]
Mais ça c'est un peu la norme dans les forums, je pense, de mettre la date de création du sujet quand on met la date comme filtre de recherche.

**Comment by Petrouchka** [comment]
En fait, pour lever l'ambiguïté, il faudrait préciser s'il s'agit d'une discussion (Top, Newest et Oldest) ou d'une réponse (Latest).
Voir https://github.com/flarum/core/issues/351

**Comment by maelsoucaze** [comment]
C'est fait, merci !

**Comment by maelsoucaze** [comment]
Le problème de dépassement est référencé sur https://github.com/flarum/core/issues/349

Je fermerai ce report lorsqu'il sera réglé (probablement pour Flarum Beta 4).

**Comment by maelsoucaze** [comment]
Corrigé avec https://github.com/flarum/flarum-ext-tags/commit/c6f9ffc57539f86b99d115e6e661b2ae16e9612e
