### ISSUE TITLE
Lettres accentuées et cédille non prises en charge dans les URLs

### ISSUE THREAD

**Issue by maelsoucaze** [maelsoucaze/flarum-ext-french#23]
Actuellement, lorsqu'on publie une discussion dont le titre comporte des lettres accentuées et la cédille utilisés en français, l'URL vers cette discussion efface ces caractères, alors qu'elle devrait les prendre en charge en remplaçant les accents et la cédille de la lettre par la lettre de l'alphabet latin.

Par exemple, le titre *Traduction française* donne l'URL :
- `https://flarum.today/fr/d/6-traduction-fran-aise`

Au lieu de :

- `https://flarum.today/fr/d/6-traduction-francaise`

Problème rapporté : https://github.com/flarum/core/issues/194

**Comment by HLFH** [comment]
Ah ce serait vraiment cool de réparer ça, c'est l'une des premières choses qu'on voit quand on utilise Flarum en français.

**Comment by maelsoucaze** [comment]
Pas d'avancement pour l'instant dans le développement depuis le 8 octobre. Ce sera, je pense, corrigé dans la version finale, mais sûrement pas dans la prochaine bêta. :)

**Comment by Fukaw** [comment]
Le problème a été soulevé sur le forum ?

**Comment by maelsoucaze** [comment]
Quel forum ?

Pouri formqtion, l'utilisation de [Stringy](https://github.com/danielstjules/Stringy) est prévue pour régler ce problème.

**Comment by unixfox** [comment]
Cette extension ne semi résoudrait pas le problème : https://discuss.flarum.org/d/3736-avatar4eg-url-transliterator ?

**Comment by maelsoucaze** [comment]
Presque, le français n'est visiblement pas encore pris en charge. De plus, je préfererai que ce soit supporté directement dans le logiciel de base que par une extension, mais c'est déjà mieux que rien !

**Comment by HLFH** [comment]
Pour moi, cette extension suffit largement. Bien entendu qu'il faudra l'implémenter à terme dans Flarum Core mais c'est déjà un ersatz suffisant.

**Comment by maelsoucaze** [comment]
Oui, et de toute façon ce bogue ne concerne pas la traduction. Merci d'avoir remonté l'extension, je ferme ce ticket !
